blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/votre-org/appv2#readme
    about: Consultez la documentation du projet
  - name: Discussions
    url: https://github.com/votre-org/appv2/discussions
    about: Posez des questions et discutez avec la communaut√©

